# Generated by Django 6.0.2 on 2026-03-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default='Debata Szkolna 2026', max_length=200)),
                ('topic', models.CharField(default='TOP 4 · Debata szkolna', max_length=200)),
                ('question', models.CharField(default='Czy szkoła powinna wprowadzić mundurki?', max_length=400)),
                ('default_speech_seconds', models.PositiveIntegerField(default=300)),
                ('current_speaker_index', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('star', models.BooleanField(default=False)),
                ('warn', models.BooleanField(default=False)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='debate.debatesettings')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
    ]
