# Generated by Django 6.0.2 on 2026-03-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatesettings',
            name='timer_remaining_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='debatesettings',
            name='timer_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debatesettings',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
