# Generated by Django 6.0.2 on 2026-03-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_debatesettings_timer_remaining_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatesettings',
            name='sound_end_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='debatesettings',
            name='sound_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debatesettings',
            name='sound_warning_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
